baseURL : "/"
languageCode : en-us
title : Famaza - Elegant Home and Bathroom Accessories
theme : hugo-sodium-theme

taxonomies:
  category: categories
  tag: tags

params:
  social:
    facebook: famaza-products
    instagram: famaza-products
    twitter: famaza-products

  scripts:
    googleanalytics:
    disqus:
